# Generated by Django 5.0.2 on 2024-03-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_to_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
