# Generated by Django 5.0.2 on 2024-03-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0002_lead_converted_to_client_alter_lead_status"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="team.team",
            ),
            preserve_default=False,
        ),
    ]
